services:
  pgvector:
    image: 'pgvector/pgvector:pg16'  # Use official pgvector image based on PostgreSQL 16
    environment:
      - 'POSTGRES_DB=ragExample'     # Name of the database to create
      - 'POSTGRES_PASSWORD=postgres' # Default password for the user
      - 'POSTGRES_USER=postgres'     # Default user with full access
    labels:
      - "org.springframework.boot.service-connection=postgres"
      # Allows Spring Boot to auto-detect this service (when using Spring Boot's Docker Compose support)
    ports:
      - '5432:5432'  # Maps container's port 5432 to host's port 5432 for PostgreSQL access
